/**
 * PDF Report Generator Service
 * Generates clinical PDF reports
 */

const PDFDocument = require('pdfkit');
const PHASES = require('../config/phases');

class PDFReportGenerator {
  /**
   * Generate PDF report stream
   */
  static generateReport(conversation, res) {
    const doc = new PDFDocument({ margin: 50 });
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition', 
      `attachment; filename=ADHD_Mission_Report_${conversation.name}_${new Date().toISOString().split('T')[0]}.pdf`
    );
    
    doc.pipe(res);
    
    const analysis = conversation.analysis || {};
    const dsmScoring = conversation.dsmScoring || {};
    
    // Header
    doc.fontSize(24).fillColor('#1DD1A1').text('NEUROFOCUS AI', { align: 'center' });
    doc.fontSize(18).fillColor('#333').text('MISSION CONTROL - Clinical Screening Report', { align: 'center' });
    doc.moveDown();
    
    // Participant Info
    doc.fontSize(12).fillColor('#666').text('─'.repeat(60));
    doc.fontSize(14).fillColor('#333').text(`Participant: ${conversation.name}`, { continued: true });
    doc.text(`   Age: ${conversation.age}`, { continued: true });
    doc.text(`   User Type: ${conversation.userType}`);
    doc.fontSize(11).fillColor('#666').text(`Date: ${new Date().toLocaleDateString()}`);
    doc.text(`Duration: ${conversation.duration || 'N/A'}`);
    doc.text(`Sectors Completed: ${conversation.sectorsUnlocked?.length || 0} / ${PHASES.length}`);
    doc.moveDown();
    
    // DSM-5 Assessment
    doc.fontSize(16).fillColor('#54A0FF').text('DSM-5 ASSESSMENT RESULTS');
    doc.fontSize(12).fillColor('#666').text('─'.repeat(60));
    doc.moveDown(0.5);
    
    // Presentation
    doc.fontSize(14).fillColor('#333');
    doc.text(`Presentation Code: `, { continued: true });
    doc.fillColor('#FF5F5F').text(dsmScoring.presentationCode || 'Subthreshold');
    doc.fontSize(11).fillColor('#666').text(dsmScoring.presentationType || 'Below Diagnostic Threshold');
    doc.moveDown();
    
    // Severity
    const severityColors = {
      minimal: '#1DD1A1',
      mild: '#FECA57',
      moderate: '#FF9F43',
      severe: '#FF5F5F'
    };
    doc.fontSize(12).fillColor('#333').text('Severity Level: ', { continued: true });
    doc.fillColor(severityColors[dsmScoring.severityLevel] || '#666')
       .text((dsmScoring.severityLevel || 'minimal').toUpperCase());
    doc.moveDown();
    
    // Scores
    doc.fontSize(12).fillColor('#333');
    doc.text(`Inattention Score: ${dsmScoring.inattentionScore || 0} / 27`);
    doc.text(`Hyperactive/Impulsive Score: ${dsmScoring.hiScore || 0} / 27`);
    doc.text(`Total Score: ${dsmScoring.totalScore || 0} / 54`);
    doc.moveDown();
    
    // Diagnostic Threshold
    doc.text(`Age-Based Threshold: ${dsmScoring.threshold || 6} symptoms`);
    doc.text(`Meets Inattention Threshold: ${dsmScoring.meetsInattentionThreshold ? 'Yes' : 'No'}`);
    doc.text(`Meets H/I Threshold: ${dsmScoring.meetsHIThreshold ? 'Yes' : 'No'}`);
    doc.moveDown();
    
    // Summary
    if (analysis.summary) {
      doc.fontSize(14).fillColor('#54A0FF').text('CLINICAL SUMMARY');
      doc.fontSize(11).fillColor('#333').text(analysis.summary, { align: 'justify' });
      doc.moveDown();
    }
    
    // Observations
    if (analysis.observations && analysis.observations.length > 0) {
      doc.fontSize(14).fillColor('#54A0FF').text('KEY OBSERVATIONS');
      for (const obs of analysis.observations) {
        doc.fontSize(11).fillColor('#333').text(`• ${obs}`);
      }
      doc.moveDown();
    }
    
    // Recommendation
    doc.fontSize(14).fillColor('#FF9F43').text('RECOMMENDATION');
    if (analysis.recommendEvaluation) {
      doc.fontSize(11).fillColor('#333')
         .text('Based on this screening, a comprehensive evaluation by a qualified healthcare professional is recommended for accurate diagnosis.', { align: 'justify' });
    } else {
      doc.fontSize(11).fillColor('#333')
         .text('This screening showed minimal concerning patterns. If concerns persist, consider consulting a healthcare professional.', { align: 'justify' });
    }
    doc.moveDown();
    
    // Disclaimer
    doc.fontSize(10).fillColor('#999');
    doc.text('─'.repeat(60));
    doc.text('DISCLAIMER: This report is generated by an AI screening tool and is NOT a clinical diagnosis. Only qualified healthcare professionals can diagnose ADHD. This screening is intended to guide discussion with clinicians and should not replace professional evaluation.', { align: 'justify' });
    
    doc.end();
  }
}

module.exports = PDFReportGenerator;
